apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: genai-app
  name: genai-app
  namespace: genai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-app
  template:
    metadata:
      labels:
        app: genai-app
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/arindam-2banerjee-0525-pimy/gcp-genai-ui/app:v0.5
        name: app
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 15
